### ISSUE TITLE
[Bug] Autocomplete variable stays after choosing a value

### ISSUE THREAD

**Issue by FL3SH** [nvim-lua/completion-nvim#123]
**My testing minimal init.vim**
```
Plug 'neovim/nvim-lsp'
Plug 'haorenW1025/completion-nvim'
...
require'nvim_lsp'.gopls.setup{on_attach=require'completion'.on_attach
```

**How to reproduce**
```
nvim main.go
fmt.<choose Print> - hint <CR>, ${1:} stays in code
```

**Expected behavior**
After choosing options from autocomplete and pressing <CR> variable `${1:}` should disappear.

**Comment by haorenW1025** [comment]
I'll try to upstream with the changes in https://github.com/neovim/neovim/pull/12118. However be aware that it's not the perfect solution. If you want a proper snippets support to still need vim-vsnip and vim-vsnip-integ. Or if you doesn't want any snippet from LSP you can turn if off by
```lua
    require'nvim-lsp'.gopls.setup({
      on_attach=require'completion'.on_attach
      capabilities = {textDocument = {completion = {completionItem = {snippetSupport = false}}}};
    })
```

**Comment by haorenW1025** [comment]
Please try #126 and see if it works for you.

**Comment by FL3SH** [comment]
Thank you, I will check it later, but the solutions with vim-vsnip and vim-vsnip-integ ars totally fine and, it solved this issue.

**Comment by haorenW1025** [comment]
I've merged it. Feel free to open other issue if you ran into other problems:)

**Comment by wbthomason** [comment]
I'm still seeing this behavior, unfortunately, and I do have `vim-vsnip` and `vim-vsnip-integ` installed and loaded.

**Comment by haorenW1025** [comment]
@wbthomason Hmm that's weird. Can you open another issue and show your minimal init.vim? Thanks:)

**Comment by FL3SH** [comment]
@wbthomason dose it actually stays after you choose an option and then hit enter?

**Comment by wbthomason** [comment]
@haorenW1025 @FL3SH I'm now having trouble replicating the issue post 22e46d3, though now I don't get *any* snippet expansion at all (i.e. I don't get the `${1:}` markers, but - for example when completing a function call with `clangd` - the completion result has the argument names/signatures filled in and places the cursor *after* the call rather than placing the cursor inside the call to fill out the arguments I want to pass).

I'll try to get a better idea of what's going on and make a new issue if I can say anything useful.

**Comment by haorenW1025** [comment]
@wbthomason Actually it is expected to not having the `${1:}` markers now because that’s the behavior in the default Omni completion. In the commit you point out I just try to align to behavior. But still you should have snippets expansion with vim-vsnip because it doesn’t care what your insert word is, the information for snippets is stored in the `user_data` of `complete-items`.

**Comment by haorenW1025** [comment]
Reference PR in Neovim core: https://github.com/neovim/neovim/pull/12118

**Comment by wbthomason** [comment]
@haorenW1025: Sorry, I’m a bit confused - you’re saying it’s expected to not get the snippet placeholders (which I understand), but then how should I trigger expansion for snippets from the LSP server?

**Comment by haorenW1025** [comment]
The snippets information stored in user_data of complete-items(see `:h complete-items`), for vim-vsnip-integ it just reads out the user_data and expand it. in `completion-nvim` I have a `CompletionDone` autocmd that call the `vim-vsnip-integ` function so it will expand the snippets if you confirm the completion.

**Comment by wbthomason** [comment]
I can no longer reproduce this; both `vim-vsnip` and `completion-nvim` have had some updates since I was able to, so it seems that something in those changes fixed whatever my issue was. Thank you!
